export const FETCH_PRICES = 'FETCH_PRICES';
export const FETCH_PRICES_SUCCEEDED = 'FETCH_PRICES_SUCCEEDED';
export const FETCH_PRICES_FAILED = 'FETCH_PRICES_FAILED';
export const PRICE_INTERVAL = 'PRICE_INTERVAL';
