export const DAPP_ID = 'teller-network';
export const EMAIL_SERVER_ENDPOINT = `http://cryptolife.status.im/api/${DAPP_ID}`;
export const EMAIL_SERVER_ENDPOINT_WITHOUT_DAPP_ID = 'https://cryptolife.status.im/api/';
export const OK = 'OK';

export const CHECK_EMAIL_SUBSCRIPTION = 'CHECK_EMAIL_SUBSCRIPTION';
export const CHECK_EMAIL_SUBSCRIPTION_SUCCESS = 'CHECK_EMAIL_SUBSCRIPTION_SUCCESS';
export const CHECK_EMAIL_SUBSCRIPTION_FAILURE = 'CHECK_EMAIL_SUBSCRIPTION_FAILURE';

export const SUBSCRIBE_EMAIL = 'SUBSCRIBE_EMAIL';
export const SUBSCRIBE_EMAIL_SUCCESS = 'SUBSCRIBE_EMAIL_SUCCESS';
export const SUBSCRIBE_EMAIL_FAILURE = 'SUBSCRIBE_EMAIL_FAILURE';

export const UNSUBSCRIBE_EMAIL = 'UNSUBSCRIBE_EMAIL';
export const UNSUBSCRIBE_EMAIL_SUCCESS = 'UNSUBSCRIBE_EMAIL_SUCCESS';
export const UNSUBSCRIBE_EMAIL_FAILURE = 'UNSUBSCRIBE_EMAIL_FAILURE';

export const HIDE_ERROR = 'HIDE_ERROR';
export const HIDE_SUCCESS = 'HIDE_SUCCESS';
export const SET_REDIRECT_TARGET = 'SET_REDIRECT_TARGET';

export const VERIFY_EMAIL = 'VERIFY_EMAIL';
export const VERIFY_EMAIL_SUCCESS = 'VERIFY_EMAIL_SUCCESS';
export const VERIFY_EMAIL_FAILURE = 'VERIFY_EMAIL_FAILURE';

export const REFUSE_EMAIL_NOTIFICATIONS = 'REFUSE_EMAIL_NOTIFICATIONS';

