export const GET_DISPUTED_ESCROWS = 'GET_DISPUTED_ESCROWS';
export const GET_DISPUTED_ESCROWS_SUCCEEDED = 'GET_DISPUTED_ESCROWS_SUCCEEDED';
export const GET_DISPUTED_ESCROWS_FAILED = 'GET_DISPUTED_ESCROWS_FAILED';

export const RESOLVE_DISPUTE = 'RESOLVE_DISPUTE';
export const RESOLVE_DISPUTE_PRE_SUCCESS = 'RESOLVE_DISPUTE_PRE_SUCCESS';
export const RESOLVE_DISPUTE_SUCCEEDED = 'RESOLVE_DISPUTE_SUCCEEDED';
export const RESOLVE_DISPUTE_FAILED = 'RESOLVE_DISPUTE_FAILED';

export const ARBITRATION_UNSOLVED = "0";
export const ARBITRATION_SOLVED_BUYER = "1"; 
export const ARBITRATION_SOLVED_SELLER = "2";

