export const GET_DISPUTED_ESCROWS = 'GET_DISPUTED_ESCROWS';
export const GET_DISPUTED_ESCROWS_SUCCEEDED = 'GET_DISPUTED_ESCROWS_SUCCEEDED';
export const GET_DISPUTED_ESCROWS_FAILED = 'GET_DISPUTED_ESCROWS_FAILED';

export const PAY_ESCROW = 'PAY_ESCROW';
export const PAY_ESCROW_SUCCEEDED = 'PAY_ESCROW_SUCCEEDED';
export const PAY_ESCROW_FAILED = 'PAY_ESCROW_FAILED';

