export const CREATE_ESCROW = 'CREATE_ESCROW';
export const CREATE_ESCROW_PRE_SUCCESS = 'CREATE_ESCROW_PRE_SUCCESS';
export const CREATE_ESCROW_SUCCEEDED = 'CREATE_ESCROW_SUCCEEDED';
export const CREATE_ESCROW_FAILED = 'CREATE_ESCROW_FAILED';

export const RESET_CREATE_ESCROW_STATUS = 'RESET_CREATE_ESCROW_STATUS';

export const GET_ESCROW = 'GET_ESCROW';
export const GET_ESCROW_SUCCEEDED = 'GET_ESCROW_SUCCEEDED';
export const GET_ESCROW_FAILED = 'GET_ESCROW_FAILED';

export const LOAD_ESCROWS = 'LOAD_ESCROWS';
export const LOAD_ESCROWS_SUCCEEDED = 'LOAD_ESCROWS_SUCCEEDED';
export const LOAD_ESCROWS_FAILED = 'LOAD_ESCROWS_FAILED';

export const RELEASE_ESCROW = 'RELEASE_ESCROW';
export const RELEASE_ESCROW_PRE_SUCCESS = 'RELEASE_ESCROW_PRE_SUCCESS';
export const RELEASE_ESCROW_SUCCEEDED = 'RELEASE_ESCROW_SUCCEEDED';
export const RELEASE_ESCROW_FAILED = 'RELEASE_ESCROW_FAILED';

export const CANCEL_ESCROW = 'CANCEL_ESCROW';
export const CANCEL_ESCROW_PRE_SUCCESS = 'CANCEL_ESCROW_PRE_SUCCESS';
export const CANCEL_ESCROW_SUCCEEDED = 'CANCEL_ESCROW_SUCCEEDED';
export const CANCEL_ESCROW_FAILED = 'CANCEL_ESCROW_FAILED';

export const RATE_TRANSACTION = 'RATE_TRANSACTION';
export const RATE_TRANSACTION_PRE_SUCCESS = 'RATE_TRANSACTION_PRE_SUCCESS';
export const RATE_TRANSACTION_SUCCEEDED = 'RATE_TRANSACTION_SUCCEEDED';
export const RATE_TRANSACTION_FAILED = 'RATE_TRANSACTION_FAILED';

export const PAY_ESCROW = 'PAY_ESCROW';
export const PAY_ESCROW_PRE_SUCCESS = 'PAY_ESCROW_PRE_SUCCESS';
export const PAY_ESCROW_SUCCEEDED = 'PAY_ESCROW_SUCCEEDED';
export const PAY_ESCROW_FAILED = 'PAY_ESCROW_FAILED';

export const PAY_ESCROW_SIGNATURE = 'PAY_ESCROW_SIGNATURE';
export const PAY_ESCROW_SIGNATURE_SUCCEEDED = 'PAY_ESCROW_SIGNATURE_SUCCEEDED';
export const PAY_ESCROW_SIGNATURE_FAILED = 'PAY_ESCROW_SIGNATURE_FAILED';

export const OPEN_CASE_SIGNATURE = 'OPEN_CASE_SIGNATURE';
export const OPEN_CASE_SIGNATURE_SUCCEEDED = 'OPEN_CASE_SIGNATURE_SUCCEEDED';
export const OPEN_CASE_SIGNATURE_FAILED = 'OPEN_CASE_SIGNATURE_FAILED';

export const OPEN_CASE = 'OPEN_CASE';
export const OPEN_CASE_PRE_SUCCESS = 'OPEN_CASE_PRE_SUCCESS';
export const OPEN_CASE_SUCCEEDED = 'OPEN_CASE_SUCCEEDED';
export const OPEN_CASE_FAILED = 'OPEN_CASE_FAILED';

export const SIGNATURE_PAYMENT = 'payment';
export const SIGNATURE_OPEN_CASE = 'open-case';

export const GET_ARBITRATION_BY_ID_SUCCEEDED = 'GET_ARBITRATION_BY_ID_SUCCEEDED';
export const GET_ARBITRATION_BY_ID_FAILED = 'GET_ARBITRATION_BY_ID_FAILED';

export const CLOSE_DIALOG = 'CLOSE_DIALOG';

export const USER_RATING = 'CHECK_USER_RATING';
export const ADD_USER_RATING = 'ADD_USER_RATING';
export const USER_RATING_SUCCEEDED = 'CHECK_USER_RATING_SUCCEEDED';
export const USER_RATING_FAILED = 'CHECK_USER_RATING_FAILED';

export const GET_FEE = 'GET_FEE';
export const GET_FEE_SUCCEEDED = 'GET_FEE_SUCCEDED';
export const GET_FEE_FAILED = 'GET_FEE_FAILED';

