export const CREATE_ESCROW = 'CREATE_ESCROW';
export const CREATE_ESCROW_SUCCEEDED = 'CREATE_ESCROW_SUCCEEDED';
export const CREATE_ESCROW_FAILED = 'CREATE_ESCROW_FAILED';

export const GET_ESCROWS = 'GET_ESCROWS';
export const GET_ESCROWS_SUCCEEDED = 'GET_ESCROWS_SUCCEEDED';
export const GET_ESCROWS_FAILED = 'GET_ESCROWS_FAILED';

export const RELEASE_ESCROW = 'RELEASE_ESCROW';
export const RELEASE_ESCROW_SUCCEEDED = 'RELEASE_ESCROW_SUCCEEDED';
export const RELEASE_ESCROW_FAILED = 'RELEASE_ESCROW_FAILED';

export const CANCEL_ESCROW = 'CANCEL_ESCROW';
export const CANCEL_ESCROW_SUCCEEDED = 'CANCEL_ESCROW_SUCCEEDED';
export const CANCEL_ESCROW_FAILED = 'CANCEL_ESCROW_FAILED';

export const RATE_TRANSACTION = 'RATE_TRANSACTION';
export const RATE_TRANSACTION_SUCCEEDED = 'RATE_TRANSACTION_SUCCEEDED';
export const RATE_TRANSACTION_FAILED = 'RATE_TRANSACTION_FAILED';

export const PAY_ESCROW = 'PAY_ESCROW';
export const PAY_ESCROW_SUCCEEDED = 'PAY_ESCROW_SUCCEEDED';
export const PAY_ESCROW_FAILED = 'PAY_ESCROW_FAILED';

export const PAY_ESCROW_SIGNATURE = 'PAY_ESCROW_SIGNATURE';
export const PAY_ESCROW_SIGNATURE_SUCCEEDED = 'PAY_ESCROW_SIGNATURE_SUCCEEDED';
export const PAY_ESCROW_SIGNATURE_FAILED = 'PAY_ESCROW_SIGNATURE_FAILED';

export const OPEN_CASE = 'OPEN_CASE';
export const OPEN_CASE_SUCCEEDED = 'OPEN_CASE_SUCCEEDED';
export const OPEN_CASE_FAILED = 'OPEN_CASE_FAILED';

export const DIALOG_PAY_SIGNATURE = 'DIALOG_PAY_SIGNATURE';
export const CLOSE_DIALOG = 'CLOSE_DIALOG';
