export const CREATE_ESCROW = 'CREATE_ESCROW';
export const CREATE_ESCROW_SUCCEEDED = 'CREATE_ESCROW_SUCCEEDED';
export const CREATE_ESCROW_FAILED = 'CREATE_ESCROW_FAILED';

export const GET_ESCROWS = 'GET_ESCROWS';
export const GET_ESCROWS_SUCCEEDED = 'GET_ESCROWS_SUCCEEDED';
export const GET_ESCROWS_FAILED = 'GET_ESCROWS_FAILED';

export const RELEASE_ESCROW = 'RELEASE_ESCROW';
export const RELEASE_ESCROW_SUCCEEDED = 'RELEASE_ESCROW_SUCCEEDED';
export const RELEASE_ESCROW_FAILED = 'RELEASE_ESCROW_FAILED';

export const CANCEL_ESCROW = 'CANCEL_ESCROW';
export const CANCEL_ESCROW_SUCCEEDED = 'CANCEL_ESCROW_SUCCEEDED';
export const CANCEL_ESCROW_FAILED = 'CANCEL_ESCROW_FAILED';
