export const BUY_LICENSE = 'BUY_LICENSE';
export const BUY_LICENSE_PRE_SUCCESS = 'BUY_LICENSE_PRE_SUCCESS';
export const BUY_LICENSE_SUCCEEDED = 'BUY_LICENSE_SUCCEEDED';
export const BUY_LICENSE_FAILED = 'BUY_LICENSE_FAILED';

export const LOAD_PRICE = 'LICENSE/LOAD_PRICE';
export const LOAD_PRICE_SUCCEEDED = 'LICENSE/LOAD_PRICE/SUCCEEDED';
export const LOAD_PRICE_FAILED = 'LICENSE/LOAD_PRICE/FAILED';

export const CHECK_LICENSE_OWNER = 'CHECK_LICENSE_OWNER';
export const CHECK_LICENSE_OWNER_SUCCEEDED = 'CHECK_LICENSE_OWNER_SUCCEEDED';
export const CHECK_LICENSE_OWNER_FAILED = 'CHECK_LICENSE_OWNER_FAILED';

export const GET_LICENSE_OWNERS = 'GET_LICENSE_OWNERS';
export const GET_LICENSE_OWNERS_SUCCCEDED = 'GET_LICENSE_OWNERS_SUCCCEDED';
export const GET_LICENSE_OWNERS_FAILED = 'GET_LICENSE_OWNERS_FAILED';
