export const BUY_LICENSE = 'BUY_LICENSE';
export const BUY_LICENSE_SUCCEEDED = 'BUY_LICENSE_SUCCEEDED';
export const BUY_LICENSE_FAILED = 'BUY_LICENSE_FAILED';

export const CHECK_LICENSE_OWNER = 'CHECK_LICENSE_OWNER';
export const CHECK_LICENSE_OWNER_SUCCEEDED = 'CHECK_LICENSE_OWNER_SUCCEEDED';
export const CHECK_LICENSE_OWNER_FAILED = 'CHECK_LICENSE_OWNER_FAILED';

