export const LOAD = 'METADATA/LOAD';
export const LOAD_SELLER = 'METADATA/LOAD_SELLER';
export const LOAD_SELLER_SUCCEEDED = 'METADATA/LOAD_SELLER/SUCCEEDED';
export const LOAD_SELLER_FAILED = 'METADATA/LOAD_SELLER/FAILED';
export const LOAD_OFFERS = 'METADATA/LOAD_MY_OFFERS';
export const LOAD_OFFERS_SUCCEEDED = 'METADATA/LOAD_MY_OFFERS/SUCCEEDED';
export const LOAD_OFFERS_FAILED = 'METADATA/LOAD_MY_OFFERS/FAILED';

