export const GET_DISPUTED_ESCROWS = 'GET_DISPUTED_ESCROWS';
export const GET_DISPUTED_ESCROWS_SUCCEEDED = 'GET_DISPUTED_ESCROWS_SUCCEEDED';
export const GET_DISPUTED_ESCROWS_FAILED = 'GET_DISPUTED_ESCROWS_FAILED';

export const RESOLVE_DISPUTE = 'RESOLVE_DISPUTE';
export const RESOLVE_DISPUTE_PRE_SUCCESS = 'RESOLVE_DISPUTE_PRE_SUCCESS';
export const RESOLVE_DISPUTE_SUCCEEDED = 'RESOLVE_DISPUTE_SUCCEEDED';
export const RESOLVE_DISPUTE_FAILED = 'RESOLVE_DISPUTE_FAILED';

export const OPEN_DISPUTE = 'OPEN_DISPUTE';
export const OPEN_DISPUTE_PRE_SUCCESS = 'OPEN_DISPUTE_PRE_SUCCESS';
export const OPEN_DISPUTE_SUCCEEDED = 'OPEN_DISPUTE_SUCCEEDED';
export const OPEN_DISPUTE_FAILED = 'OPEN_DISPUTE_FAILED';

export const ARBITRATION_UNSOLVED = "0";
export const ARBITRATION_SOLVED_BUYER = "1"; 
export const ARBITRATION_SOLVED_SELLER = "2";

export const LOAD_ARBITRATION = 'LOAD_ARBITRATION';
export const LOAD_ARBITRATION_SUCCEEDED = 'LOAD_ARBITRATION_SUCCEEDED';
export const LOAD_ARBITRATION_FAILED = 'LOAD_ARBITRATION_FAILED';

export const GET_ARBITRATORS = 'GET_ARBITRATORS';
export const GET_ARBITRATORS_SUCCEEDED = 'GET_ARBITRATORS_SUCCEEDED';
export const GET_ARBITRATORS_FAILED = 'GET_ARBITRATORS_FAILED';

export const BUY_LICENSE = 'BUY_ARB_LICENSE';
export const BUY_LICENSE_PRE_SUCCESS = 'BUY_ARB_LICENSE_PRE_SUCCESS';
export const BUY_LICENSE_SUCCEEDED = 'BUY_ARB_LICENSE_SUCCEEDED';
export const BUY_LICENSE_FAILED = 'BUY_ARB_LICENSE_FAILED';

export const LOAD_PRICE = 'ARBITRATION/LOAD_PRICE';
export const LOAD_PRICE_SUCCEEDED = 'ARBITRATION/LOAD_PRICE/SUCCEEDED';
export const LOAD_PRICE_FAILED = 'ARBITRATION/LOAD_PRICE/FAILED';

export const CHECK_LICENSE_OWNER = 'CHECK_ARB_LICENSE_OWNER';
export const CHECK_LICENSE_OWNER_SUCCEEDED = 'CHECK_ARB_LICENSE_OWNER_SUCCEEDED';
export const CHECK_LICENSE_OWNER_FAILED = 'CHECK_ARB_LICENSE_OWNER_FAILED';

