export const INIT = 'NETWORK/INIT';
export const INIT_SUCCEEDED = 'NETWORK/INIT/SUCCEEDED';
export const INIT_FAILED = 'NETWORK/INIT/FAILED';

export const RESET_STATE = 'RESET_STATE';
export const PURGE_STATE = 'PURGE_STATE';

export const UPDATE_BALANCES = 'NETWORK/UPDATE_BALANCES';
export const UPDATE_BALANCE = 'NETWORK/UPDATE_BALANCE';
export const UPDATE_BALANCE_SUCCEEDED = 'NETWORK/UPDATE_BALANCE/SUCCEEDED';
export const UPDATE_BALANCE_FAILED = 'NETWORK/UPDATE_BALANCE/FAILED';

export const GET_CONTACT_CODE = 'NETWORK/GET_CONTACT_CODE';
export const GET_CONTACT_CODE_SUCCEEDED = 'NETWORK/GET_CONTACT_CODE/SUCCEEDED';
export const GET_CONTACT_CODE_FAILED = 'NETWORK/GET_CONTACT_CODE/FAILED';

export const GET_GAS_PRICE = 'NETWORK/GET_GAS_PRICE';
export const GET_GAS_PRICE_SUCCEEDED = 'NETWORK/GET_GAS_PRICE_SUCCEEDED';
export const GET_GAS_PRICE_FAILED = 'NETWORK/GET_GAS_PRICE_FAILED';

export const RESOLVE_ENS_NAME = 'NETWORK/RESOLVE_ENS_NAME';
export const RESOLVE_ENS_NAME_SUCCEEDED = 'NETWORK/RESOLVE_ENS_NAME/SUCCEEDED';
export const RESOLVE_ENS_NAME_FAILED = 'NETWORK/RESOLVE_ENS_NAME/FAILED';
