export const INIT = 'NETWORK/INIT';
export const INIT_SUCCEEDED = 'NETWORK/INIT/SUCCEEDED';
export const INIT_FAILED = 'NETWORK/INIT/FAILED';

export const UPDATE_BALANCES = 'NETWORK/UPDATE_BALANCES';
export const UPDATE_BALANCE = 'NETWORK/UPDATE_BALANCE';
export const UPDATE_BALANCE_SUCCEEDED = 'NETWORK/UPDATE_BALANCE/SUCCEEDED';
export const UPDATE_BALANCE_FAILED = 'NETWORK/UPDATE_BALANCE/FAILED';

