export const UPDATE_BALANCES = 'BALANCES/UPDATE_BALANCES';
export const UPDATE_BALANCE = 'BALANCES/UPDATE_BALANCE';
export const UPDATE_BALANCE_SUCCEEDED = 'BALANCES/UPDATE_BALANCE/SUCCEEDED';
export const UPDATE_BALANCE_FAILED = 'BALANCES/UPDATE_BALANCE/FAILED';

