export const LOAD_SNT_BALANCE = 'BALANCES/LOAD_SNT_BALANCE';
export const LOAD_SNT_BALANCE_SUCCEEDED = 'BALANCES/LOAD_SNT_BALANCE/SUCCEEDED';
export const LOAD_SNT_BALANCE_FAILED = 'BALANCES/LOAD_SNT_BALANCE/FAILED';

