export const SET_FIAT = 'SET_FIAT';
export const SET_MARGIN = 'SET_MARGIN';
export const SET_SELECTED_ASSET = 'SET_SELECTED_ASSET';
export const SET_LOCATION = 'SET_LOCATION';
export const SET_PAYMENT_METHODS = 'SET_PAYMENT_METHODS';
