export const APPROVE_TOKEN = 'APPROVAL/APPROVE_TOKEN';

export const APPROVE_PRE_SUCCEEDED = 'APPROVAL/APPROVE_PRE_SUCCEEDED';
export const APPROVE_SUCCEEDED = 'APPROVAL/APPROVE_SUCCEEDED';
export const APPROVE_FAILED = 'APPROVAL/APPROVE_FAILED';
